"""add columns to addresses table

Revision ID: 7fab27e0559f
Revises: 
Create Date: 2025-12-10 16:23:20.795664

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7fab27e0559f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted! ###
    op.add_column('addresses', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('addresses', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('addresses', sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted! ###
    op.drop_column('addresses', 'province')
    op.drop_column('addresses', 'phone_number')alem
    op.drop_column('addresses', 'label')
    # ### end Alembic commands ###
